(declare (unit rtorrent-commands))
(declare (uses rtorrent-connection))

;; next is definition of varios rtorrent commands (methods for <rtorrent-connection> class)
;; symbol 'torrent-or-hash substituted with call (calculate-torrent-hash torrent)
(define-syntax rt:cmd
  (lambda (x r c)
    (let* ((method (cadr x))
           (name (string->symbol (string-append "rt:" method)))
           (args (cddr x))
           (%define (r 'define))
           (%lambda (r 'lambda)))
      `(,%define ,name (,%lambda (connection ,@args) (send connection ,method ,@args))))))

;; (define-syntax rt:method
;;   (lambda (x r c)
;;     (let* ((method (cadr x))
;;            (name (string->symbol (string-append "rt:" method)))
;;            (args (cddr x))
;;            (%calculate-torrent-hash (r 'calculate-torrent-hash))
;;            (subs-args (map
;;                        (lambda (sym)
;;                          (if (eq? sym 'torrent-or-hash)
;;                              `(,%calculate-torrent-hash torrent-or-hash)
;;                              sym))
;;                        args))
;;            (%<rtorrent-connection> (r '<rtorrent-connection>))
;;            (%define-method (r 'define-method))
;;            (%lambda (r 'lambda)))
;;       `(,%define-method (,name (connection ,%<rtorrent-connection>) ,@args) (send connection ,method ,@subs-args)))))

;; system methods
;; (rt:method "system.listMethods")
;; (rt:method "system.hostname")
;; (rt:method "system.pid")
;; (rt:method "system.client_version")
;; (rt:method "system.library_version")

;; (rt:method "download_list")
;; (rt:method "load_raw" raw-torrent-blob)
;; (rt:method "d.base_path" torrent-hash)
;; (rt:method "d.get_directory" torrent-hash)
;; (rt:method "d.set_directory" torrent-hash base-path)
;; (rt:method "d.state" torrent-hash)
;; (rt:method "d.start" torrent-hash)
;; (rt:method "d.stop" torrent-hash)

(rt:cmd "system.listMethods")
(rt:cmd "system.hostname")
(rt:cmd "system.pid")
(rt:cmd "system.client_version")
(rt:cmd "system.library_version")

(rt:cmd "download_list" view)
(rt:cmd "load_raw" raw-torrent-blob)

(rt:cmd "d.base_path" torrent-hash)
(rt:cmd "d.get_directory" torrent-hash)
(rt:cmd "d.set_directory" torrent-hash base-path)
(rt:cmd "d.state" torrent-hash)
(rt:cmd "d.start" torrent-hash)
(rt:cmd "d.stop" torrent-hash)
(rt:cmd "d.erase" torrent-hash)
(rt:cmd "d.base_filename" torrent-hash)
(rt:cmd "d.base_path" torrent-hash)
(rt:cmd "d.bitfield" torrent-hash)
(rt:cmd "d.bytes_done" torrent-hash)
(rt:cmd "d.check_hash" torrent-hash)
(rt:cmd "d.chunk_size" torrent-hash)
(rt:cmd "d.chunks_hashed" torrent-hash)
(rt:cmd "d.close" torrent-hash)
(rt:cmd "d.close.directly" torrent-hash)
(rt:cmd "d.complete" torrent-hash)
(rt:cmd "d.completed_bytes" torrent-hash)
(rt:cmd "d.completed_chunks" torrent-hash)
(rt:cmd "d.connection_current" torrent-hash)
(rt:cmd "d.connection_current.set" torrent-hash)
(rt:cmd "d.connection_leech" torrent-hash)
(rt:cmd "d.connection_seed" torrent-hash)
(rt:cmd "d.create_link" torrent-hash)
(rt:cmd "d.creation_date" torrent-hash)
(rt:cmd "d.custom" torrent-hash)
(rt:cmd "d.custom.set" torrent-hash)
(rt:cmd "d.custom1" torrent-hash)
(rt:cmd "d.custom1.set" torrent-hash)
(rt:cmd "d.custom2" torrent-hash)
(rt:cmd "d.custom2.set" torrent-hash)
(rt:cmd "d.custom3" torrent-hash)
(rt:cmd "d.custom3.set" torrent-hash)
(rt:cmd "d.custom4" torrent-hash)
(rt:cmd "d.custom4.set" torrent-hash)
(rt:cmd "d.custom5" torrent-hash)
(rt:cmd "d.custom5.set" torrent-hash)
(rt:cmd "d.custom_throw" torrent-hash)
(rt:cmd "d.delete_link" torrent-hash)
(rt:cmd "d.delete_tied" torrent-hash)
(rt:cmd "d.directory" torrent-hash)
(rt:cmd "d.directory.set" torrent-hash)
(rt:cmd "d.directory_base" torrent-hash)
(rt:cmd "d.directory_base.set" torrent-hash)
(rt:cmd "d.down.choke_heuristics" torrent-hash)
(rt:cmd "d.down.choke_heuristics.leech" torrent-hash)
(rt:cmd "d.down.choke_heuristics.seed" torrent-hash)
(rt:cmd "d.down.choke_heuristics.set" torrent-hash)
(rt:cmd "d.down.rate" torrent-hash)
(rt:cmd "d.down.total" torrent-hash)
(rt:cmd "d.erase" torrent-hash)
(rt:cmd "d.free_diskspace" torrent-hash)
(rt:cmd "d.get_base_filename" torrent-hash)
(rt:cmd "d.get_base_path" torrent-hash)
(rt:cmd "d.get_bitfield" torrent-hash)
(rt:cmd "d.get_bytes_done" torrent-hash)
(rt:cmd "d.get_chunk_size" torrent-hash)
(rt:cmd "d.get_chunks_hashed" torrent-hash)
(rt:cmd "d.get_complete" torrent-hash)
(rt:cmd "d.get_completed_bytes" torrent-hash)
(rt:cmd "d.get_completed_chunks" torrent-hash)
(rt:cmd "d.get_connection_current" torrent-hash)
(rt:cmd "d.get_connection_leech" torrent-hash)
(rt:cmd "d.get_connection_seed" torrent-hash)
(rt:cmd "d.get_creation_date" torrent-hash)
(rt:cmd "d.get_custom" torrent-hash)
(rt:cmd "d.get_custom1" torrent-hash)
(rt:cmd "d.get_custom2" torrent-hash)
(rt:cmd "d.get_custom3" torrent-hash)
(rt:cmd "d.get_custom4" torrent-hash)
(rt:cmd "d.get_custom5" torrent-hash)
(rt:cmd "d.get_custom_throw" torrent-hash)
(rt:cmd "d.get_directory" torrent-hash)
(rt:cmd "d.get_directory_base" torrent-hash)
(rt:cmd "d.get_down_rate" torrent-hash)
(rt:cmd "d.get_down_total" torrent-hash)
(rt:cmd "d.get_free_diskspace" torrent-hash)
(rt:cmd "d.get_hash" torrent-hash)
(rt:cmd "d.get_hashing" torrent-hash)
(rt:cmd "d.get_hashing_failed" torrent-hash)
(rt:cmd "d.get_ignore_commands" torrent-hash)
(rt:cmd "d.get_left_bytes" torrent-hash)
(rt:cmd "d.get_loaded_file" torrent-hash)
(rt:cmd "d.get_local_id" torrent-hash)
(rt:cmd "d.get_local_id_html" torrent-hash)
(rt:cmd "d.get_max_file_size" torrent-hash)
(rt:cmd "d.get_max_size_pex" torrent-hash)
(rt:cmd "d.get_message" torrent-hash)
(rt:cmd "d.get_mode" torrent-hash)
(rt:cmd "d.get_name" torrent-hash)
(rt:cmd "d.get_peer_exchange" torrent-hash)
(rt:cmd "d.get_peers_accounted" torrent-hash)
(rt:cmd "d.get_peers_complete" torrent-hash)
(rt:cmd "d.get_peers_connected" torrent-hash)
(rt:cmd "d.get_peers_max" torrent-hash)
(rt:cmd "d.get_peers_min" torrent-hash)
(rt:cmd "d.get_peers_not_connected" torrent-hash)
(rt:cmd "d.get_priority" torrent-hash)
(rt:cmd "d.get_priority_str" torrent-hash)
(rt:cmd "d.get_ratio" torrent-hash)
(rt:cmd "d.get_size_bytes" torrent-hash)
(rt:cmd "d.get_size_chunks" torrent-hash)
(rt:cmd "d.get_size_files" torrent-hash)
(rt:cmd "d.get_size_pex" torrent-hash)
(rt:cmd "d.get_skip_rate" torrent-hash)
(rt:cmd "d.get_skip_total" torrent-hash)
(rt:cmd "d.get_state" torrent-hash)
(rt:cmd "d.get_state_changed" torrent-hash)
(rt:cmd "d.get_state_counter" torrent-hash)
(rt:cmd "d.get_throttle_name" torrent-hash)
(rt:cmd "d.get_tied_to_file" torrent-hash)
(rt:cmd "d.get_tracker_focus" torrent-hash)
(rt:cmd "d.get_tracker_numwant" torrent-hash)
(rt:cmd "d.get_tracker_size" torrent-hash)
(rt:cmd "d.get_up_rate" torrent-hash)
(rt:cmd "d.get_up_total" torrent-hash)
(rt:cmd "d.get_uploads_max" torrent-hash)
(rt:cmd "d.group" torrent-hash)
(rt:cmd "d.group.set" torrent-hash)
(rt:cmd "d.hash" torrent-hash)
(rt:cmd "d.hashing" torrent-hash)
(rt:cmd "d.hashing_failed" torrent-hash)
(rt:cmd "d.hashing_failed.set" torrent-hash)
(rt:cmd "d.ignore_commands" torrent-hash)
(rt:cmd "d.ignore_commands.set" torrent-hash)
(rt:cmd "d.incomplete" torrent-hash)
(rt:cmd "d.initialize_logs" torrent-hash)
(rt:cmd "d.is_active" torrent-hash)
(rt:cmd "d.is_hash_checked" torrent-hash)
(rt:cmd "d.is_hash_checking" torrent-hash)
(rt:cmd "d.is_multi_file" torrent-hash)
(rt:cmd "d.is_open" torrent-hash)
(rt:cmd "d.is_pex_active" torrent-hash)
(rt:cmd "d.is_private" torrent-hash)
(rt:cmd "d.left_bytes" torrent-hash)
(rt:cmd "d.load_date" torrent-hash)
(rt:cmd "d.loaded_file" torrent-hash)
(rt:cmd "d.local_id" torrent-hash)
(rt:cmd "d.local_id_html" torrent-hash)
(rt:cmd "d.max_file_size" torrent-hash)
(rt:cmd "d.max_file_size.set" torrent-hash)
(rt:cmd "d.max_size_pex" torrent-hash)
(rt:cmd "d.message" torrent-hash)
(rt:cmd "d.message.set" torrent-hash)
(rt:cmd "d.mode" torrent-hash)
(rt:cmd "d.multicall" torrent-hash)
(rt:cmd "d.multicall2" torrent-hash)
(rt:cmd "d.name" torrent-hash)
(rt:cmd "d.open" torrent-hash)
(rt:cmd "d.pause" torrent-hash)
(rt:cmd "d.peer_exchange" torrent-hash)
(rt:cmd "d.peer_exchange.set" torrent-hash)
(rt:cmd "d.peers_accounted" torrent-hash)
(rt:cmd "d.peers_complete" torrent-hash)
(rt:cmd "d.peers_connected" torrent-hash)
(rt:cmd "d.peers_max" torrent-hash)
(rt:cmd "d.peers_max.set" torrent-hash)
(rt:cmd "d.peers_min" torrent-hash)
(rt:cmd "d.peers_min.set" torrent-hash)
(rt:cmd "d.peers_not_connected" torrent-hash)
(rt:cmd "d.priority" torrent-hash)
(rt:cmd "d.priority.set" torrent-hash)
(rt:cmd "d.priority_str" torrent-hash)
(rt:cmd "d.ratio" torrent-hash)
(rt:cmd "d.resume" torrent-hash)
(rt:cmd "d.save_full_session" torrent-hash)
(rt:cmd "d.save_resume" torrent-hash)
(rt:cmd "d.set_connection_current" torrent-hash)
(rt:cmd "d.set_custom" torrent-hash)
(rt:cmd "d.set_custom1" torrent-hash)
(rt:cmd "d.set_custom2" torrent-hash)
(rt:cmd "d.set_custom3" torrent-hash)
(rt:cmd "d.set_custom4" torrent-hash)
(rt:cmd "d.set_custom5" torrent-hash)
(rt:cmd "d.set_directory" torrent-hash)
(rt:cmd "d.set_directory_base" torrent-hash)
(rt:cmd "d.set_hashing_failed" torrent-hash)
(rt:cmd "d.set_ignore_commands" torrent-hash)
(rt:cmd "d.set_max_file_size" torrent-hash)
(rt:cmd "d.set_message" torrent-hash)
(rt:cmd "d.set_peers_max" torrent-hash)
(rt:cmd "d.set_peers_min" torrent-hash)
(rt:cmd "d.set_priority" torrent-hash)
(rt:cmd "d.set_throttle_name" torrent-hash)
(rt:cmd "d.set_tied_to_file" torrent-hash)
(rt:cmd "d.set_tracker_numwant" torrent-hash)
(rt:cmd "d.set_uploads_max" torrent-hash)
(rt:cmd "d.size_bytes" torrent-hash)
(rt:cmd "d.size_chunks" torrent-hash)
(rt:cmd "d.size_files" torrent-hash)
(rt:cmd "d.size_pex" torrent-hash)
(rt:cmd "d.skip.rate" torrent-hash)
(rt:cmd "d.skip.total" torrent-hash)
(rt:cmd "d.start" torrent-hash)
(rt:cmd "d.state" torrent-hash)
(rt:cmd "d.state_changed" torrent-hash)
(rt:cmd "d.state_counter" torrent-hash)
(rt:cmd "d.stop" torrent-hash)
(rt:cmd "d.throttle_name" torrent-hash)
(rt:cmd "d.throttle_name.set" torrent-hash)
(rt:cmd "d.tied_to_file" torrent-hash)
(rt:cmd "d.tied_to_file.set" torrent-hash)
(rt:cmd "d.timestamp.finished" torrent-hash)
(rt:cmd "d.tracker_announce" torrent-hash)
(rt:cmd "d.tracker_focus" torrent-hash)
(rt:cmd "d.tracker_numwant" torrent-hash)
(rt:cmd "d.tracker_numwant.set" torrent-hash)
(rt:cmd "d.tracker_size" torrent-hash)
(rt:cmd "d.try_close" torrent-hash)
(rt:cmd "d.try_start" torrent-hash)
(rt:cmd "d.try_stop" torrent-hash)
(rt:cmd "d.up.choke_heuristics" torrent-hash)
(rt:cmd "d.up.choke_heuristics.leech" torrent-hash)
(rt:cmd "d.up.choke_heuristics.seed" torrent-hash)
(rt:cmd "d.up.choke_heuristics.set" torrent-hash)
(rt:cmd "d.up.rate" torrent-hash)
(rt:cmd "d.up.total" torrent-hash)
(rt:cmd "d.update_priorities" torrent-hash)
(rt:cmd "d.uploads_max" torrent-hash)
(rt:cmd "d.uploads_max.set" torrent-hash)
(rt:cmd "d.views" torrent-hash)
(rt:cmd "d.views.has" torrent-hash)
(rt:cmd "d.views.push_back" torrent-hash)
(rt:cmd "d.views.push_back_unique" torrent-hash)
(rt:cmd "d.views.remove" torrent-hash)
